# Generated by Django 2.2.2 on 2019-07-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20190727_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='right_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='total_right_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='total_wrong_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
